modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"

[[mods]]
modId = "sedna"
version = "${version}"
displayName = "Sedna for Minecraft"
logoFile = "logo.png"
authors = "Sangar, SirDavidLudwig"
description = '''
RISC-V Virtual Machine and binary images for computer mods.
This mod contains a Linux distribution built from the "sedna" branch of the following repository:
  https://github.com/fnuecke/buildroot
The licenses for the embedded software are embedded in the JAR file containing this mod, inside the "licenses" directory.
'''

[[dependencies.oc2-sedna]]
modId = "forge"
mandatory = true
versionRange = "[40.0.40,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.oc2-sedna]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"
